Private events
uryelah/Microverse-507-Private-Events pull request #1
Opened 2019-12-26 18:01 UTC by uryelah

This is an events site project, similar to Eventbrite, done with ruby on rails that allows users to create events, send invites to their hosted or attending events and confirm their presence for the events they were invited to. 
- Sign up and log in to access the events, invites and users routes.
- Create an event and send invites to other users
- Receive and accept an invite to an event to be able to attend it and send invites for it
- Cancel your attendance to an event to destroy your invitation
- An event invite cannot be sent to its creator
- A user cannot send an invite to an event held past the current time

2019-12-26 18:38 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

1. Please implement the following in the **UsersController `show` action** and not in the **views' helpers**:

* [x] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)).

2. * [x] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers, [check](http://codefol.io/posts/Where-Do-I-Put-My-Code) this for reference, [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png).

3. The tests are **red** please make them **green**:
<img width="823" alt="Screen Shot 2019-12-26 at 1 38 15 PM" src="https://user-images.githubusercontent.com/33462180/71486564-fc787180-27e4-11ea-8750-e41f3faa5192.png">

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-12-28 00:11 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Great work on this project, however, the following issues need to be fixed before moving on ⬇️** 

1. I tried to access the project but I'm getting the following error: 

<img width="1209" alt="Screen Shot 2019-12-27 at 7 06 37 PM" src="https://user-images.githubusercontent.com/33462180/71536347-0e890b80-28dc-11ea-9d69-245e09e49060.png">

2. **Automated Tests:**
* [x] The models should have unit tests for validations and associations **(Rspec)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)).
* [x] The authentication needs to have integration tests **(Rspec + Capybara)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)).
* [x] Event managment features need have integration tests **(Rspec + Capybara)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)).

- You could refer to my [article on here](https://hackernoon.com/test-driven-development-with-rspec-in-rails-gsr3zrs) about testing if you don't know how to implement Rspec and Capybara.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-12-30 21:24 UTC, samgaco approved these changes
Hi @uryelah and @jairjy :high_brightness: 

The error indicated in the previous review is not showing anymore and integration & unit test were added. You can move on :ballot_box_with_check: 

Well done with the tests by the way :+1: 

Keep up the good work! 

------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-12-30 21:24 UTC, samgaco commented on spec/models/event_spec.rb
> +
:medal_military:

2020-01-07 15:24 UTC, merged